//--------------------------
#SPEAKER_ID "FFFFFF"
@adsdfsadfsdfasdfsa
{
<NS>asdfsadfsa<NE>
<BUSTUP 0 0 0>
<VOICE "sadfsdfds">
dsafdsfds
<WAIT>
}
//--------------------------
#SPEAKER_ID "FFFFFF"
@adsdfsadfsdfasdfsa
{
<NS>asdfsadfsa<NE>
<BUSTUP 0 0 0>
<VOICE "sadfsdfds">
dsafdsfds
<WAIT>
}
//--------------------------
#SPEAKER_ID "FFFFFF"
@adsdfsadfsdfasdfsa
{
<NS>asdfsadfsa<NE>
<BUSTUP 0 0 0>
<VOICE "sadfsdfds">
dsafdsfds
<WAIT>
}